# Generated by Django 4.0.3 on 2022-03-11 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_todo_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='redacted',
            field=models.BooleanField(default=False),
        ),
    ]
